2025-03-21 11:42:59,955 : INFO : root : Loading config.
2025-03-21 11:42:59,966 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-03-21 11:42:59,967 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\cadfdee4981114acd6fff59d1071b59b.mpf_cache
2025-03-21 11:43:00,112 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\ee7db1e8d011f44c876692bb4657f2e9.mpf_cache
2025-03-21 11:43:00,127 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\9f058d482eac17116727d62a93500be7.mpf_cache
2025-03-21 11:43:00,141 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\2c9362052ff91db960f514d041b7f4e4.mpf_cache
2025-03-21 11:43:00,151 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\9e006ea23aa21ec68e01f6c49afad9f4.mpf_cache
2025-03-21 11:43:00,166 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\fd253b339e263587268891c4dd997fbd.mpf_cache
2025-03-21 11:43:00,181 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\c114ce798d07012a33b8b14d8f953bb7.mpf_cache
2025-03-21 11:43:00,198 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\ef70c2e65c3659b77bacdd3a7a24b233.mpf_cache
2025-03-21 11:43:00,218 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\ec6e376f0ea10a5fdf8f7130b4bbbe7c.mpf_cache
2025-03-21 11:43:00,241 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0
2025-03-21 11:43:00,242 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-03-21-11-42-59-mpf-T0SHIII.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-03-21 11:43:00,242 : INFO : Machine : MPF path: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf
2025-03-21 11:43:00,242 : INFO : Machine : Machine path: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine
2025-03-21 11:43:00,242 : INFO : Machine : Platform: win32
2025-03-21 11:43:00,242 : INFO : Machine : Python executable location: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\python.exe
2025-03-21 11:43:00,242 : INFO : Machine : Python version: 3.11.0 (64-bit)
2025-03-21 11:43:00,246 : INFO : Machine : Initializing MPF...
2025-03-21 11:43:01,028 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-03-21 11:43:01,235 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-03-21 11:43:01,236 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 8000, 'prev_value': None, 'change': True}
2025-03-21 11:43:01,236 : INFO : EventManager : Event: ======'machine_var_player2_score'====== Args={'value': 1000, 'prev_value': None, 'change': True}
2025-03-21 11:43:01,236 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0', 'prev_value': None, 'change': True}
2025-03-21 11:43:01,237 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-03-21 11:43:01,237 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.11.0', 'prev_value': None, 'change': True}
2025-03-21 11:43:01,256 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-03-21 11:43:01,256 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-03-21 11:43:01,256 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-03-21 11:43:01,256 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-03-21 11:43:01,256 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-03-21 11:43:01,256 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-03-21 11:43:01,280 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-03-21 11:43:01,280 : INFO : SwitchController : Found active switch: ('3', <Platform.SmartVirtual>) <switch.s_trough1>
2025-03-21 11:43:01,280 : INFO : SwitchController : Found active switch: ('4', <Platform.SmartVirtual>) <switch.s_trough2>
2025-03-21 11:43:01,280 : INFO : SwitchController : Found active switch: ('5', <Platform.SmartVirtual>) <switch.s_trough3>
2025-03-21 11:43:01,282 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2025-03-21 11:43:01,284 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2025-03-21 11:43:32,809 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2025-03-21 11:43:32,813 : INFO : EventManager : Event: ======'machine_var_mc_version'====== Args={'value': 'MPF-MC v0.57.1', 'prev_value': None, 'change': True}
2025-03-21 11:43:32,815 : INFO : EventManager : Event: ======'machine_var_mc_extended_version'====== Args={'value': 'MPF-MC v0.57.1 (config_version=6, BCP v1.1,                      Requires MPF API compatibility v0.57.0 or newer)', 'prev_value': None, 'change': True}
2025-03-21 11:43:32,822 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2025-03-21 11:43:32,860 : ERROR : asyncio : Exception in callback DelayManager._process_delay_callback('draw_screen', <bound method...0187EB6EFE00>>)()
handle: <TimerHandle when=255488.869 DelayManager._process_delay_callback('draw_screen', <bound method...0187EB6EFE00>>)()>
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 751, in _run_handlers
    result = handler.callback(**merged_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\text_ui.py", line 462, in _bcp_connected
    self.scene.remove_effect(self._pending_bcp_connection)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\asciimatics\scene.py", line 85, in remove_effect
    self._effects.remove(effect)
ValueError: list.remove(x): x not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\delays.py", line 190, in _process_delay_callback
    self.machine.events.process_event_queue()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 842, in process_event_queue
    self._process_event(event=event[0],
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 804, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 753, in _run_handlers
    raise EventHandlerException(
mpf.core.events.EventHandlerException: Exception while processing RegisteredHandler(callback=<bound method TextUi._bcp_connected of <mpf.core.text_ui.TextUi object at 0x00000187EB6EFE00>>, priority=1, kwargs={}, key=UUID('b28c55af-4ffe-414e-972c-9fc06db07d0e'), condition=None, blocking_facility=None) for event bcp_clients_connected. list.remove(x): x not in list
2025-03-21 11:43:33,031 : INFO : ball_device.bd_trough : BCH: Initial count: 3
2025-03-21 11:43:33,031 : INFO : Machine : Starting the main run loop.
2025-03-21 11:43:33,032 : INFO : ball_device.bd_trough : State: idle
2025-03-21 11:43:33,032 : INFO : Machine : Shutting down...
2025-03-21 11:43:33,033 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-03-21 11:43:33,036 : INFO : ball_device.bd_plunger_lane : BCH: Initial count: 0
2025-03-21 11:43:33,037 : INFO : ball_device.bd_plunger_lane : State: idle
2025-03-21 11:43:33,096 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-03-21 11:43:33,148 : INFO : EventManager : Event: ======'init_phase_4'====== Args={}
2025-03-21 11:43:33,150 : ERROR : asyncio : Exception in callback Util.raise_exceptions(<Task finishe...unt_stable'")>) at C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\utility_functions.py:790
handle: <Handle Util.raise_exceptions(<Task finishe...unt_stable'")>) at C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\utility_functions.py:790>
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\utility_functions.py", line 798, in raise_exceptions
    future.result()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\ball_controller.py", line 90, in _add_new_balls_to_playfield
    self.num_balls_known = await self._count_all_balls_in_devices()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\ball_controller.py", line 129, in _count_all_balls_in_devices
    futures.append(asyncio.ensure_future(device.ball_count_handler.counter.wait_for_count_stable()))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'wait_for_count_stable'
2025-03-21 11:43:33,237 : INFO : EventManager : Event: ======'machine_var_audits_events_game_ended'====== Args={'value': 13, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,238 : INFO : EventManager : Event: ======'machine_var_audits_events_game_started'====== Args={'value': 52, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,239 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_drain'====== Args={'value': 6, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,239 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough1'====== Args={'value': 5, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,240 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough2'====== Args={'value': 8, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,241 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough3'====== Args={'value': 12, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,243 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough_enter'====== Args={'value': 7, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,243 : INFO : EventManager : Event: ======'machine_var_audits_player_score'====== Args={'value': {'average': 124, 'top': [8000, 1000, 0, 0, 0, 0, 0, 0, 0, 0], 'total': 16}, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,244 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Lane1'====== Args={'value': 36, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,245 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Lane2'====== Args={'value': 25, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,245 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Lane3'====== Args={'value': 22, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,246 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Lane4'====== Args={'value': 26, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,247 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Target1'====== Args={'value': 66, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,247 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Target2'====== Args={'value': 59, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,248 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Target3'====== Args={'value': 64, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,250 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Target4'====== Args={'value': 51, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,250 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_drain'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,251 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_launcher_button'====== Args={'value': 92, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,252 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_left_flipper'====== Args={'value': 103, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,253 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_playfield_entry'====== Args={'value': 201, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,253 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_plunger_lane'====== Args={'value': 136, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,254 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_pointTarget'====== Args={'value': 193, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,255 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_right_flipper'====== Args={'value': 95, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,256 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough1'====== Args={'value': 109, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,257 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough2'====== Args={'value': 17, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,258 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough3'====== Args={'value': 14, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,258 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_enter'====== Args={'value': 1, 'prev_value': None, 'change': True}
2025-03-21 11:43:33,261 : INFO : EventManager : Event: ======'init_phase_5'====== Args={}
2025-03-21 11:43:33,263 : ERROR : asyncio : Task was destroyed but it is pending!
task: <Task pending name='Task-76' coro=<IocpProactor.accept.<locals>.accept_coro() running at C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\windows_events.py:591> wait_for=<_OverlappedFuture cancelled>>
2025-03-21 11:43:33,265 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 751, in _run_handlers
    result = handler.callback(**merged_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\text_ui.py", line 462, in _bcp_connected
    self.scene.remove_effect(self._pending_bcp_connection)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\asciimatics\scene.py", line 85, in remove_effect
    self._effects.remove(effect)
ValueError: list.remove(x): x not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 794, in _run_loop
    raise self._exception['exception']
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\delays.py", line 190, in _process_delay_callback
    self.machine.events.process_event_queue()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 842, in process_event_queue
    self._process_event(event=event[0],
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 804, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 753, in _run_handlers
    raise EventHandlerException(
mpf.core.events.EventHandlerException: Exception while processing RegisteredHandler(callback=<bound method TextUi._bcp_connected of <mpf.core.text_ui.TextUi object at 0x00000187EB6EFE00>>, priority=1, kwargs={}, key=UUID('b28c55af-4ffe-414e-972c-9fc06db07d0e'), condition=None, blocking_facility=None) for event bcp_clients_connected. list.remove(x): x not in list
2025-03-21 11:45:01,534 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 751, in _run_handlers
    result = handler.callback(**merged_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\text_ui.py", line 462, in _bcp_connected
    self.scene.remove_effect(self._pending_bcp_connection)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\asciimatics\scene.py", line 85, in remove_effect
    self._effects.remove(effect)
ValueError: list.remove(x): x not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 794, in _run_loop
    raise self._exception['exception']
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\delays.py", line 190, in _process_delay_callback
    self.machine.events.process_event_queue()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 842, in process_event_queue
    self._process_event(event=event[0],
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 804, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 753, in _run_handlers
    raise EventHandlerException(
mpf.core.events.EventHandlerException: Exception while processing RegisteredHandler(callback=<bound method TextUi._bcp_connected of <mpf.core.text_ui.TextUi object at 0x00000187EB6EFE00>>, priority=1, kwargs={}, key=UUID('b28c55af-4ffe-414e-972c-9fc06db07d0e'), condition=None, blocking_facility=None) for event bcp_clients_connected. list.remove(x): x not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\commands\game.py", line 240, in __init__
    self.machine.run()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 690, in run
    self._run_loop()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 797, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError
