2025-03-05 21:15:57,362 : INFO : root : Loading config.
2025-03-05 21:15:57,364 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-03-05 21:15:57,366 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\config\config.yaml
2025-03-05 21:15:57,366 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\mpfconfig.yaml.
2025-03-05 21:15:57,375 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\mpfconfig.yaml
2025-03-05 21:15:57,375 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\config\config.yaml.
2025-03-05 21:15:57,391 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\config\config.yaml
2025-03-05 21:15:57,392 : INFO : ConfigProcessor : Config file cache created: C:\Users\duffb\AppData\Local\Temp\cadfdee4981114acd6fff59d1071b59b.mpf_cache
2025-03-05 21:15:57,464 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\2d51d76727b268a801d8dd7a18b89879.mpf_cache
2025-03-05 21:15:57,465 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\9f058d482eac17116727d62a93500be7.mpf_cache
2025-03-05 21:15:57,465 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0
2025-03-05 21:15:57,465 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-03-05-21-15-57-mpf-T0SHIII.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-03-05 21:15:57,465 : INFO : Machine : MPF path: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf
2025-03-05 21:15:57,465 : INFO : Machine : Machine path: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine
2025-03-05 21:15:57,465 : INFO : Machine : Platform: win32
2025-03-05 21:15:57,465 : INFO : Machine : Python executable location: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\python.exe
2025-03-05 21:15:57,465 : INFO : Machine : Python version: 3.11.0 (64-bit)
2025-03-05 21:15:57,467 : INFO : Machine : Initializing MPF...
2025-03-05 21:15:57,620 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-03-05 21:15:57,677 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-03-05 21:15:57,677 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0', 'prev_value': None, 'change': True}
2025-03-05 21:15:57,677 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-03-05 21:15:57,677 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.11.0', 'prev_value': None, 'change': True}
2025-03-05 21:15:57,699 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-03-05 21:15:57,699 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-03-05 21:15:57,699 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-03-05 21:15:57,699 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-03-05 21:15:57,699 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-03-05 21:15:57,699 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-03-05 21:15:57,725 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-03-05 21:15:57,725 : INFO : SwitchController : Found active switch: ('8', <Platform.SmartVirtual>) <switch.s_trough_enter>
2025-03-05 21:15:57,726 : INFO : SwitchController : Found active switch: ('7', <Platform.SmartVirtual>) <switch.s_trough1>
2025-03-05 21:15:57,726 : INFO : SwitchController : Found active switch: ('10', <Platform.SmartVirtual>) <switch.s_trough2>
2025-03-05 21:15:57,726 : INFO : SwitchController : Found active switch: ('11', <Platform.SmartVirtual>) <switch.s_trough3>
2025-03-05 21:15:57,727 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2025-03-05 21:15:57,728 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2025-03-05 21:15:59,783 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2025-03-05 21:15:59,784 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2025-03-05 21:15:59,872 : INFO : ball_device.bd_drain : BCH: Initial count: 0
2025-03-05 21:15:59,872 : INFO : ball_device.bd_drain : State: idle
2025-03-05 21:15:59,873 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-51' coro=<BallDevice._initialize_async() done, defined at C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\ball_device.py:196> exception=ConfigFileError('Cannot use capacity and ball switches.')>
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\ball_device.py", line 198, in _initialize_async
    await self.ball_count_handler.initialize()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\ball_count_handler.py", line 92, in initialize
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\switch_counter.py", line 90, in __init__
    self.ball_device.raise_config_error("Cannot use capacity and ball switches.", 3)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_trough: Cannot use capacity and ball switches. Error Code: CFE-ball_device-3 (https://missionpinball.org/logs)
2025-03-05 21:15:59,875 : INFO : ball_device.bd_plunger_lane : BCH: Initial count: 0
2025-03-05 21:15:59,875 : INFO : Machine : Starting the main run loop.
2025-03-05 21:15:59,875 : INFO : ball_device.bd_plunger_lane : State: idle
2025-03-05 21:15:59,876 : INFO : Machine : Shutting down...
2025-03-05 21:15:59,876 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-03-05 21:15:59,884 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-03-05 21:15:59,887 : INFO : EventManager : Event: ======'init_phase_4'====== Args={}
2025-03-05 21:15:59,887 : ERROR : asyncio : Exception in callback Util.raise_exceptions(<Task finishe...unt_stable'")>) at C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\utility_functions.py:790
handle: <Handle Util.raise_exceptions(<Task finishe...unt_stable'")>) at C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\utility_functions.py:790>
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\utility_functions.py", line 798, in raise_exceptions
    future.result()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\ball_controller.py", line 90, in _add_new_balls_to_playfield
    self.num_balls_known = await self._count_all_balls_in_devices()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\ball_controller.py", line 129, in _count_all_balls_in_devices
    futures.append(asyncio.ensure_future(device.ball_count_handler.counter.wait_for_count_stable()))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'wait_for_count_stable'
2025-03-05 21:15:59,890 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough3'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-05 21:15:59,890 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_launcher_button'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-05 21:15:59,890 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_playfield_entry'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-05 21:15:59,891 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough1'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-05 21:15:59,891 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_drain'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-05 21:15:59,891 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough2'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-05 21:15:59,891 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_right_flipper'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-05 21:15:59,892 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_left_flipper'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-05 21:15:59,892 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_plunger_lane'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-05 21:15:59,892 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_enter'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-05 21:15:59,892 : INFO : EventManager : Event: ======'machine_var_audits_events_game_started'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-05 21:15:59,892 : INFO : EventManager : Event: ======'machine_var_audits_events_game_ended'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-05 21:15:59,892 : INFO : EventManager : Event: ======'machine_var_audits_player_score'====== Args={'value': {'top': [], 'average': 0, 'total': 0}, 'prev_value': None, 'change': True}
2025-03-05 21:15:59,893 : INFO : EventManager : Event: ======'init_phase_5'====== Args={}
2025-03-05 21:16:00,905 : ERROR : asyncio : Task was destroyed but it is pending!
task: <Task pending name='Task-69' coro=<IocpProactor.accept.<locals>.accept_coro() running at C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\windows_events.py:591> wait_for=<_OverlappedFuture cancelled>>
2025-03-05 21:16:00,906 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 794, in _run_loop
    raise self._exception['exception']
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\ball_device.py", line 198, in _initialize_async
    await self.ball_count_handler.initialize()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\ball_count_handler.py", line 92, in initialize
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\switch_counter.py", line 90, in __init__
    self.ball_device.raise_config_error("Cannot use capacity and ball switches.", 3)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_trough: Cannot use capacity and ball switches. Error Code: CFE-ball_device-3 (https://missionpinball.org/logs)
2025-03-05 21:16:05,445 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 794, in _run_loop
    raise self._exception['exception']
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\ball_device.py", line 198, in _initialize_async
    await self.ball_count_handler.initialize()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\ball_count_handler.py", line 92, in initialize
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\switch_counter.py", line 90, in __init__
    self.ball_device.raise_config_error("Cannot use capacity and ball switches.", 3)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_trough: Cannot use capacity and ball switches. Error Code: CFE-ball_device-3 (https://missionpinball.org/logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\commands\game.py", line 240, in __init__
    self.machine.run()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 690, in run
    self._run_loop()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 797, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError
