2025-02-24 12:01:37,009 : INFO : root : Loading config.
2025-02-24 12:01:37,012 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-02-24 12:01:37,013 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\Machine\config\config.yaml
2025-02-24 12:01:37,013 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\mpfconfig.yaml.
2025-02-24 12:01:37,063 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\mpfconfig.yaml
2025-02-24 12:01:37,064 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\Machine\config\config.yaml.
2025-02-24 12:01:37,088 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\Machine\config\config.yaml
2025-02-24 12:01:37,089 : INFO : ConfigProcessor : Config file cache created: C:\Users\duffb\AppData\Local\Temp\3afaa59cec570166c159ef3ccf39e5f9.mpf_cache
2025-02-24 12:01:37,259 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\575906dbe7623207645ae67e92bb8aef.mpf_cache
2025-02-24 12:01:37,260 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\f89525c9467937f322df736101ec6dd8.mpf_cache
2025-02-24 12:01:37,260 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev6
2025-02-24 12:01:37,260 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-02-24-12-01-37-mpf-T0SHIII.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'full_logfile_path': 'C:\\Users\\duffb\\OneDrive\\Documents\\Python Envs\\PinballWW1\\Machine\\logs\\2025-02-24-12-01-37-mpf-T0SHIII.log'}
2025-02-24 12:01:37,260 : INFO : Machine : MPF path: C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf
2025-02-24 12:01:37,261 : INFO : Machine : Machine path: C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\Machine
2025-02-24 12:01:37,261 : INFO : Machine : Platform: win32
2025-02-24 12:01:37,261 : INFO : Machine : Python executable location: C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\Scripts\python.exe
2025-02-24 12:01:37,261 : INFO : Machine : Python version: 3.13.1 (64-bit)
2025-02-24 12:01:37,262 : INFO : Machine : Initializing MPF...
2025-02-24 12:01:37,342 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-02-24 12:01:37,363 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-02-24 12:01:37,363 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev6', 'prev_value': None, 'change': True}
2025-02-24 12:01:37,363 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev6, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-02-24 12:01:37,364 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.13.1', 'prev_value': None, 'change': True}
2025-02-24 12:01:37,650 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-11-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-02-24 12:01:37,651 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-02-24 12:01:37,651 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '11', 'prev_value': None, 'change': True}
2025-02-24 12:01:37,651 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-02-24 12:01:37,651 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-02-24 12:01:37,652 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Users\\duffb\\OneDrive\\Documents\\Python Envs\\PinballWW1\\Machine\\logs\\2025-02-24-12-01-37-mpf-T0SHIII.log', 'prev_value': None, 'change': True}
2025-02-24 12:01:37,652 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-02-24 12:01:37,699 : ERROR : asyncio : Exception in callback EventManager._async_handler_done()() at C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\events.py:124
handle: <Handle EventManager._async_handler_done()() at C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\events.py:124>
Traceback (most recent call last):
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
    ~~~~~~~~~~~~~^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\device_manager.py", line 88, in _load_device_modules
    self.load_devices_config(validate=True)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\device_manager.py", line 146, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.config_section, config, self.name, "device", prefix=debug_prefix)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                 validation_failure_info=validation_failure_info)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~^
        this_spec[k], item=source[k],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        validation_failure_info=ValidationPath(validation_failure_info, k))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\config_validator.py", line 243, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\config_validator.py", line 413, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
                                'Device "{}" not found in "{}:" section in your config.'.format(item, param),
                                6)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry flippers:left_flipper:main_coil = "c_flipper_left_main" is not valid. Device "c_flipper_left_main" not found in "coils:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2025-02-24 12:01:37,707 : INFO : Machine : Starting the main run loop with active modes: []
2025-02-24 12:01:37,707 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-02-24 12:01:37,708 : INFO : Machine : Shutting down...
2025-02-24 12:01:37,708 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-02-24 12:01:38,712 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\machine.py", line 808, in _run_loop
    raise self._exception['exception']
  File "C:\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
    ~~~~~~~~~~~~~^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\device_manager.py", line 88, in _load_device_modules
    self.load_devices_config(validate=True)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\device_manager.py", line 146, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.config_section, config, self.name, "device", prefix=debug_prefix)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                 validation_failure_info=validation_failure_info)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~^
        this_spec[k], item=source[k],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        validation_failure_info=ValidationPath(validation_failure_info, k))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\config_validator.py", line 243, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\OneDrive\Documents\Python Envs\PinballWW1\mpf\mpf\core\config_validator.py", line 413, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
                                'Device "{}" not found in "{}:" section in your config.'.format(item, param),
                                6)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry flippers:left_flipper:main_coil = "c_flipper_left_main" is not valid. Device "c_flipper_left_main" not found in "coils:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2025-02-24 12:01:38,725 : INFO : root : MPF run loop ended.
