2025-02-24 14:18:39,970 : INFO : root : Loading config.
2025-02-24 14:18:39,973 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-02-24 14:18:39,974 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\config\config.yaml
2025-02-24 14:18:39,974 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\mpfconfig.yaml.
2025-02-24 14:18:39,984 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\mpfconfig.yaml
2025-02-24 14:18:39,984 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\config\config.yaml.
2025-02-24 14:18:40,006 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\config\config.yaml
2025-02-24 14:18:40,007 : INFO : ConfigProcessor : Config file cache created: C:\Users\duffb\AppData\Local\Temp\cadfdee4981114acd6fff59d1071b59b.mpf_cache
2025-02-24 14:18:40,093 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\2d51d76727b268a801d8dd7a18b89879.mpf_cache
2025-02-24 14:18:40,094 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\9f058d482eac17116727d62a93500be7.mpf_cache
2025-02-24 14:18:40,095 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0
2025-02-24 14:18:40,095 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-02-24-14-18-39-mpf-T0SHIII.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-02-24 14:18:40,095 : INFO : Machine : MPF path: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf
2025-02-24 14:18:40,095 : INFO : Machine : Machine path: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine
2025-02-24 14:18:40,095 : INFO : Machine : Platform: win32
2025-02-24 14:18:40,095 : INFO : Machine : Python executable location: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\python.exe
2025-02-24 14:18:40,095 : INFO : Machine : Python version: 3.11.0 (64-bit)
2025-02-24 14:18:40,097 : INFO : Machine : Initializing MPF...
2025-02-24 14:18:40,282 : ERROR : ConfigValidator : Your config contains a value for the setting "machine:virtual_platform_start_active_switches", but this is not a valid setting name.
2025-02-24 14:18:40,282 : INFO : Machine : Shutting down...
2025-02-24 14:18:40,283 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-02-24 14:18:40,283 : ERROR : Machine : Failed to initialize MPF
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 676, in initialize_mpf
    raise init.exception()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 247, in initialize
    await self.initialize_core_and_hardware()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 238, in initialize_core_and_hardware
    self._validate_config()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 369, in _validate_config
    self.validate_machine_config_section('machine')
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 381, in validate_machine_config_section
    self.config[section] = self.config_validator.validate_config(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\config_validator.py", line 336, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "machine:virtual_platform_start_active_switches", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2025-02-24 14:19:17,290 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 676, in initialize_mpf
    raise init.exception()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 247, in initialize
    await self.initialize_core_and_hardware()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 238, in initialize_core_and_hardware
    self._validate_config()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 369, in _validate_config
    self.validate_machine_config_section('machine')
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 381, in validate_machine_config_section
    self.config[section] = self.config_validator.validate_config(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\config_validator.py", line 336, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "machine:virtual_platform_start_active_switches", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\commands\game.py", line 240, in __init__
    self.machine.run()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 686, in run
    if not self.initialize_mpf():
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 679, in initialize_mpf
    report_crash(init.exception(), "init_exception", self.config)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError
