2025-03-06 22:37:14,300 : INFO : root : Loading config.
2025-03-06 22:37:14,303 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-03-06 22:37:14,304 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\cadfdee4981114acd6fff59d1071b59b.mpf_cache
2025-03-06 22:37:14,384 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\attract\config\attract.yaml
2025-03-06 22:37:14,385 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\modes\attract\config\attract.yaml.
2025-03-06 22:37:14,386 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\modes\attract\config\attract.yaml
2025-03-06 22:37:14,386 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\attract\config\attract.yaml.
2025-03-06 22:37:14,401 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\attract\config\attract.yaml
2025-03-06 22:37:14,401 : INFO : ConfigProcessor : Config file cache created: C:\Users\duffb\AppData\Local\Temp\ee7db1e8d011f44c876692bb4657f2e9.mpf_cache
2025-03-06 22:37:14,402 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\9f058d482eac17116727d62a93500be7.mpf_cache
2025-03-06 22:37:14,402 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\9e006ea23aa21ec68e01f6c49afad9f4.mpf_cache
2025-03-06 22:37:14,403 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\attract\shows\.\attract_display_loop.yaml
2025-03-06 22:37:14,403 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\attract\shows\.\attract_display_loop.yaml.
2025-03-06 22:37:14,427 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\attract\shows\.\attract_display_loop.yaml
2025-03-06 22:37:14,428 : INFO : ConfigProcessor : Config file cache created: C:\Users\duffb\AppData\Local\Temp\fd253b339e263587268891c4dd997fbd.mpf_cache
2025-03-06 22:37:14,428 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0
2025-03-06 22:37:14,428 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-03-06-22-37-14-mpf-T0SHIII.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-03-06 22:37:14,428 : INFO : Machine : MPF path: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf
2025-03-06 22:37:14,428 : INFO : Machine : Machine path: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine
2025-03-06 22:37:14,428 : INFO : Machine : Platform: win32
2025-03-06 22:37:14,428 : INFO : Machine : Python executable location: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\python.exe
2025-03-06 22:37:14,428 : INFO : Machine : Python version: 3.11.0 (64-bit)
2025-03-06 22:37:14,430 : INFO : Machine : Initializing MPF...
2025-03-06 22:37:14,866 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-03-06 22:37:14,907 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-03-06 22:37:14,907 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 8000, 'prev_value': None, 'change': True}
2025-03-06 22:37:14,907 : INFO : EventManager : Event: ======'machine_var_player2_score'====== Args={'value': 1000, 'prev_value': None, 'change': True}
2025-03-06 22:37:14,907 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0', 'prev_value': None, 'change': True}
2025-03-06 22:37:14,907 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-03-06 22:37:14,907 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.11.0', 'prev_value': None, 'change': True}
2025-03-06 22:37:14,928 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-03-06 22:37:14,928 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-03-06 22:37:14,928 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-03-06 22:37:14,928 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-03-06 22:37:14,928 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-03-06 22:37:14,928 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-03-06 22:37:14,940 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-03-06 22:37:14,940 : INFO : SwitchController : Found active switch: ('3', <Platform.SmartVirtual>) <switch.s_trough1>
2025-03-06 22:37:14,940 : INFO : SwitchController : Found active switch: ('4', <Platform.SmartVirtual>) <switch.s_trough2>
2025-03-06 22:37:14,940 : INFO : SwitchController : Found active switch: ('5', <Platform.SmartVirtual>) <switch.s_trough3>
2025-03-06 22:37:14,942 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2025-03-06 22:37:14,944 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2025-03-06 22:37:17,000 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2025-03-06 22:37:17,002 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2025-03-06 22:37:17,342 : INFO : EventManager : Event: ======'machine_var_mc_version'====== Args={'value': 'MPF-MC v0.57.1', 'prev_value': None, 'change': True}
2025-03-06 22:37:17,343 : INFO : EventManager : Event: ======'machine_var_mc_extended_version'====== Args={'value': 'MPF-MC v0.57.1 (config_version=6, BCP v1.1,                      Requires MPF API compatibility v0.57.0 or newer)', 'prev_value': None, 'change': True}
2025-03-06 22:37:17,346 : INFO : ball_device.bd_trough : BCH: Initial count: 3
2025-03-06 22:37:17,480 : INFO : ball_device.bd_trough : State: idle
2025-03-06 22:37:17,496 : INFO : ball_device.bd_plunger_lane : BCH: Initial count: 0
2025-03-06 22:37:17,498 : INFO : ball_device.bd_plunger_lane : State: idle
2025-03-06 22:37:17,539 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-03-06 22:37:17,543 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...ute 'items'")>)
handle: <Handle EventManager._queue_task_done(<Task finishe...ute 'items'")>)>
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 64, in _validate_config_item
    device_settings['widgets'] = self.process_widgets(
                                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 92, in process_widgets
    widget_list.append(self.process_widget(widget))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 128, in process_widget
    config['animations'] = self.process_animations(
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 139, in process_animations
    for event_name, event_settings in config.items():
                                      ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'
2025-03-06 22:37:17,584 : INFO : Machine : Starting the main run loop.
2025-03-06 22:37:17,585 : INFO : Machine : Shutting down...
2025-03-06 22:37:17,585 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-03-06 22:37:18,604 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 794, in _run_loop
    raise self._exception['exception']
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 64, in _validate_config_item
    device_settings['widgets'] = self.process_widgets(
                                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 92, in process_widgets
    widget_list.append(self.process_widget(widget))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 128, in process_widget
    config['animations'] = self.process_animations(
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 139, in process_animations
    for event_name, event_settings in config.items():
                                      ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'
2025-03-06 22:37:21,463 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 794, in _run_loop
    raise self._exception['exception']
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 64, in _validate_config_item
    device_settings['widgets'] = self.process_widgets(
                                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 92, in process_widgets
    widget_list.append(self.process_widget(widget))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 128, in process_widget
    config['animations'] = self.process_animations(
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpfmc\config_players\plugins\slide_player.py", line 139, in process_animations
    for event_name, event_settings in config.items():
                                      ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\commands\game.py", line 240, in __init__
    self.machine.run()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 690, in run
    self._run_loop()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 797, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError
