2025-02-24 14:21:16,672 : INFO : root : Loading config.
2025-02-24 14:21:16,675 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-02-24 14:21:16,675 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\config\config.yaml
2025-02-24 14:21:16,675 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\mpfconfig.yaml.
2025-02-24 14:21:16,684 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\mpfconfig.yaml
2025-02-24 14:21:16,684 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\config\config.yaml.
2025-02-24 14:21:16,704 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\config\config.yaml
2025-02-24 14:21:16,705 : INFO : ConfigProcessor : Config file cache created: C:\Users\duffb\AppData\Local\Temp\cadfdee4981114acd6fff59d1071b59b.mpf_cache
2025-02-24 14:21:16,783 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\2d51d76727b268a801d8dd7a18b89879.mpf_cache
2025-02-24 14:21:16,783 : INFO : ConfigProcessor : Loading config from cache: C:\Users\duffb\AppData\Local\Temp\9f058d482eac17116727d62a93500be7.mpf_cache
2025-02-24 14:21:16,784 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0
2025-02-24 14:21:16,784 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-02-24-14-21-16-mpf-T0SHIII.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-02-24 14:21:16,784 : INFO : Machine : MPF path: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf
2025-02-24 14:21:16,784 : INFO : Machine : Machine path: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine
2025-02-24 14:21:16,784 : INFO : Machine : Platform: win32
2025-02-24 14:21:16,784 : INFO : Machine : Python executable location: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\python.exe
2025-02-24 14:21:16,784 : INFO : Machine : Python version: 3.11.0 (64-bit)
2025-02-24 14:21:16,786 : INFO : Machine : Initializing MPF...
2025-02-24 14:21:16,938 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-02-24 14:21:16,980 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-02-24 14:21:16,981 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0', 'prev_value': None, 'change': True}
2025-02-24 14:21:16,981 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-02-24 14:21:16,981 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.11.0', 'prev_value': None, 'change': True}
2025-02-24 14:21:16,990 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-02-24 14:21:16,990 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-02-24 14:21:16,990 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-02-24 14:21:16,990 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-02-24 14:21:16,990 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-02-24 14:21:16,990 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-02-24 14:21:17,000 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-02-24 14:21:17,002 : INFO : ball_device.bd_drain : BCH: Initial count: 0
2025-02-24 14:21:17,002 : INFO : ball_device.bd_drain : State: idle
2025-02-24 14:21:17,002 : INFO : ball_device.bd_trough : BCH: Initial count: 0
2025-02-24 14:21:17,003 : INFO : ball_device.bd_trough : State: idle
2025-02-24 14:21:17,003 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-50' coro=<BallDevice._initialize_async() done, defined at C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\ball_device.py:196> exception=ConfigFileError('Config validation error: Entry ball_device_counter_ball_switches:ball_device_counter_ball_switches:ball_switches = "s_plunger" is not valid. Device "s_plunger" not found in "switches:" section in your config.')>
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\ball_device.py", line 198, in _initialize_async
    await self.ball_count_handler.initialize()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\ball_count_handler.py", line 92, in initialize
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\devices\ball_device\switch_counter.py", line 27, in __init__
    self.config = self.machine.config_validator.validate_config("ball_device_counter_ball_switches", self.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\config_validator.py", line 205, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\config_validator.py", line 257, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\config_validator.py", line 683, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\config_validator.py", line 401, in _validate_type_machine
    return self.validation_error(item, validation_failure_info,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\config_validator.py", line 700, in validation_error
    raise ConfigFileError("Config validation error: Entry {} = \"{}\" is not valid. {}".format(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_device_counter_ball_switches:ball_device_counter_ball_switches:ball_switches = "s_plunger" is not valid. Device "s_plunger" not found in "switches:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2025-02-24 14:21:17,010 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-02-24 14:21:17,011 : INFO : Machine : Starting the main run loop.
2025-02-24 14:21:17,011 : INFO : EventManager : Event: ======'init_phase_4'====== Args={}
2025-02-24 14:21:17,012 : INFO : Machine : Shutting down...
2025-02-24 14:21:17,012 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-02-24 14:21:17,012 : ERROR : root : no running event loop
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\commands\game.py", line 240, in __init__
    self.machine.run()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 690, in run
    self._run_loop()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 790, in _run_loop
    self._crash_shutdown()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 735, in _crash_shutdown
    self._do_stop()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 725, in _do_stop
    self.events.process_event_queue()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 838, in process_event_queue
    self._process_queue_event(event=event[0],
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 779, in _process_queue_event
    task = asyncio.create_task(self._run_handlers_sequential(event, callback, kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\tasks.py", line 371, in create_task
    loop = events.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
